---
title: "Sex Prediction"
author: "Shannon E. Ellis"
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{recount quick start guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r vignetteSetup, echo=FALSE, message=FALSE, warning = FALSE}
## Track time spent on making the vignette
startTime <- Sys.time()
```
# Load libraries

```{r load-packages, message = FALSE, warning = FALSE}
## load libraries
library(devtools)
# install_github("leekgroup/phenopredict")
document("/users/sellis/phenopredict")
library('phenopredict')
library(rtracklayer)
library(recount)
library('R.utils')
library('BiocParallel')

## Set colors
## import colors to use
  bright= c(red=rgb(222,45,38, maxColorValue=255), #de2d26
            pink=rgb( 255, 102, 153, maxColorValue=255), #ff6699
            orange=rgb(232,121,12, maxColorValue=255),   #e8790c
            yellow=rgb(255,222,13, maxColorValue=255), #ffde0d          
            green=rgb(12,189,24, maxColorValue=255),  #0cbd18           
            teal=rgb(59,196,199, maxColorValue=255), #3bc4c7
            blue=rgb(58,158,234, maxColorValue=255), #3a9eea
            purple=rgb(148,12,232, maxColorValue=255)) #940ce8  
```

# Load data and filter regions
```{r 'load-data-filter-regions', message = FALSE, warning = FALSE}
load("/dcl01/leek/data/sellis/barcoding/data/sample_individuals.Rdata")
load("/dcl01/leek/data/sellis/barcoding/data/rda/gtexmetadata.rda")
gtex_meta = gtexmetadata
gtex_meta = cbind(gtex_meta,usegtex)
rm(gtexmetadata,usegtex)
gtex_meta[is.na(gtex_meta[,"SMTS"]),"SMTS"] <- c("Esophagus","Skin","Stomach","Skin","Esophagus")
usegtex = gtex_meta$usegtex
  pheno = gtex_meta
  pheno = pheno[usegtex,]

#unique indidivudals
  length(unique(pheno$dbGaP_Sample_ID))
  pheno = pheno[sample_individuals,]



if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/merge_input_Sex_nocovars.rda")){
# prepare expression data
source("/dcs01/ajaffe/GTEX/Leek/coverageMatrix/simpleLoad/gtexLoad.R")
chrs = c("X","Y")
for(i in 1:length(chrs)){
  chrname=paste0("chr",chrs[i])    
  cat(paste0(chrname,"..."))
  dat = gtexLoad(chrname)
  pheno = gtex_meta
  cm = dat$coverageMatrix
  regiondata = dat$regions
  cm = log2(cm + 1)
  wid = width(dat$regions)

  pheno = pheno[usegtex,]
  cm = cm[, usegtex]
  cm_all=cm[wid>20,]
  regiondata = regiondata[wid>20]
  cm_regiondata = regiondata
  #only include the half of samples used for building the predictor
  pheno = pheno[sample_individuals,]
  cm = cm_all[,sample_individuals]
  cm_new = cm_all[,-sample_individuals]
  assign(paste0("cm_new",'_',chrname),cm_new)
  assign(paste0("cm_regiondata",'_',chrname),cm_regiondata)

# number of regions in expression data 
nrow(cm)

# number of samples included in example
ncol(cm)

inputdata<-filter_regions(expression=cm, regiondata=regiondata ,phenodata=pheno, phenotype="Sex",
    covariates=NULL,type="factor",numRegions=100)

assign(paste0("inputdata",'_',chrname),inputdata)
}
save(cm_new_chrX, cm_new_chrY, file="/dcl01/leek/data/sellis/barcoding/data/cm_new_Sex_nocovars.Rda")
save(cm_regiondata_chrX, cm_regiondata_chrY, file="/dcl01/leek/data/sellis/barcoding/data/cm_regiondata_Sex_nocovars.Rda")
}
```

# Merge input data

```{r 'merge-inputdata', message = FALSE, warning = FALSE}
if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/merge_input_Sex_nocovars.rda")){
  merge_input<- merge_input(inputdata_list=list(inputdata_chrX, inputdata_chrY))
  save(merge_input, file="/dcl01/leek/data/sellis/barcoding/data/merge_input_Sex_nocovars.rda")
}else{
  load("/dcl01/leek/data/sellis/barcoding/data/merge_input_Sex_nocovars.rda")
}
# save(merge_input, file="data/merge_input_Sex.rda")
# taking a look at output of merge_input
dim(merge_input$covmat)
merge_input$regiondata
```


# Build predictor

```{r 'build-predictor', message = FALSE, warning = FALSE}
predictor<-build_predictor(inputdata=merge_input ,phenodata=pheno, phenotype="Sex", 
    covariates=NULL,type="factor",numRegions=20)
# save(predictor,file="data/predictor_Sex_nocovars.rda")

#number of probes used for prediction
length(predictor$trainingProbes)

#this contains the coefficient estimates used for prediction. 
# the number of rows corresponds to the number of sites used for prediction
# while the columns corresponds to the number of categories of your phenotype.
dim(predictor$coefEsts)
```

# Plot expression by sex at a few regions

```{r 'expression', fig.width=8, fig.height=8}
# ov <-  findOverlaps(predictor$regiondata,merge_input$regiondata)
# index_regions <- subjectHits(ov)
#reorder GRanges objects
# dm  <- merge_input$covmat[index_regions,]
# rd <- merge_input$regiondata[index_regions]

dm = merge_input$covmat
rd = merge_input$regiondata
par(mfrow=c(2,2)) 
toplot = c(1,2,21,22)
for (i in toplot){
  female = as.numeric(dm[i,pheno$Sex=="female"])
  male = as.numeric(dm[i,pheno$Sex=="male"])
  region = names(rd[i])
  plot(density(female),xlab="log2(Normalized Expression + 1)",
       ylab="Density",cex.lab=1.2,cex.axis=1.2,,col=bright["purple"],main=region,lwd=2)
    lines(density(male),col=bright["teal"],lwd=3)
  }
   legend("topright",legend=c("female","male"),col=c(bright["purple"],bright["teal"]),bty="n",lwd=2,cex=1.2)

```

# Test predictor

```{r 'test-predictor', message = FALSE, warning = FALSE}
predictions_test <-test_predictor(inputdata=merge_input ,phenodata=pheno, phenotype="Sex", 
    covariates=NULL,type="factor",predictordata=predictor )
# number of samples
length(predictions_test$predicted)

# get summary of how prediction is doing
predictions_test$summarized

actual = predictions_test$actual
predicted = predictions_test$predicted
perc_correct = predictions_test$summarized[,"percent_correct"]


#get output for package
predictions_gtex = as.data.frame(cbind(pheno$Run,"gtex",actual=as.character(actual),predicted,perc_correct))

```

# Extract data

```{r 'extract-data', message = FALSE, warning = FALSE}
# looking at the input data for extract_data
     load("/dcl01/leek/data/sellis/barcoding/data/cm_new_Sex_nocovars.Rda")
     load("/dcl01/leek/data/sellis/barcoding/data/cm_regiondata_Sex_nocovars.Rda")

    new_chrX<-extract_data(newexpression=cm_new_chrX, newregiondata=cm_regiondata_chrX, predictordata=predictor)
    new_chrY<-extract_data(newexpression=cm_new_chrY, newregiondata=cm_regiondata_chrY, predictordata=predictor)

    merge_test<- merge_input(inputdata_list=list(new_chrX, new_chrY))

  ov <- findOverlaps(predictor$regiondata,merge_test$regiondata)
  index_regions <- subjectHits(ov)
  #reorder GRanges objects
  merge_test$regiondata <- merge_test$regiondata[index_regions]
  merge_test$covmat <- merge_test$covmat[index_regions,]

```

# Predict phenotype in GTEx

```{r 'predict-phenotype', message = FALSE, warning = FALSE}

predictions<-predict_pheno(inputdata_test= merge_test, phenodata=pheno, phenotype="Sex", covariates=NULL,type="factor", predictordata = predictor)
# number of samples
length(predictions)

#since we know the truth here, let's check and see how we're doing:
 
 #pull out actual Sex
  pheno2 = gtex_meta
  pheno2 = pheno2[usegtex,]
  pheno2 = pheno2[-sample_individuals,]
  actual = pheno2$Sex

  #define predicted
  predicted = predictions

  #summarize data
	number_match <- sum(predicted==actual)
	perc_correct = sum(predicted==actual)/length(actual)
	number_sites = nrow(predictor$coefEsts)

	summarized = c(number_sites,number_match, perc_correct)
	names(summarized) <- c("sites_tested", "number_correct", "percent_correct")
 
 #compare predictions to known sex
 summarized

#get output for package
predictions_gtex_test = as.data.frame(cbind(pheno2$Run,"gtex",actual=as.character(actual),predicted,perc_correct))
predictions_gtex$perc_correct <- perc_correct
```


# Predict phenotype in TCGA

```{r 'predict-sra', message = FALSE, warning = FALSE}
regions = predictor$regiondata

# get phenotype info in order
recount::all_metadata('TCGA') -> md 
bws = gsub('.bw','', md$bigwig_file)

if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/TCGA_Sex_inputdata.rda")) {

  ## Extract same regions from TCGA data
  load('/dcl01/lieber/ajaffe/lab/gtex_ers/rse_TCGA.Rdata')
  findOverlaps(regions,rse) -> ov
  ## extract regions from predictor
  rse[subjectHits(ov)] -> rse_sub
  ## get coverage matrix ; order same as in regions
  ## note: these aren't scaled
  cov_tcga <- assays(rse_sub)$counts

  


  #ensure covmat is in same order as regions
  if( identical(tolower(bws),colnames(cov_tcga) )==TRUE){
    covmat= cov_tcga
    regions = regions

    #remove coverage samples for which we don't have metadata
    covmat = covmat[,colnames(covmat) %in% tolower(bws)]

    #put data on a log2 scale
    dm = log2(covmat+1)
  }else{
    message("metadata and expression data not in same order")
  }

  TCGA_inputdata=c()
  TCGA_inputdata$covmat <- dm
  TCGA_inputdata$regiondata <- predictor$regiondata

    ov <- findOverlaps(predictor$regiondata,TCGA_inputdata$regiondata)
    index_regions <- subjectHits(ov)
    #reorder GRanges objects
    TCGA_inputdata$regiondata <- TCGA_inputdata$regiondata[index_regions]
    TCGA_inputdata$covmat <- TCGA_inputdata$covmat[index_regions,]

    save(TCGA_inputdata, md, file="/dcl01/leek/data/sellis/barcoding/data/TCGA_Sex_inputdata.rda")
}else{
  load("/dcl01/leek/data/sellis/barcoding/data/TCGA_Sex_inputdata.rda")
}

  predictions<-predict_pheno(inputdata_test= TCGA_inputdata, phenodata=pheno, phenotype="Sex", covariates=NULL,type="factor", predictordata = predictor)
  # number of samples
  length(predictions)


  md2 = md[!is.na(md$gdc_cases.demographic.gender),]

  actual_all = as.character(md$gdc_cases.demographic.gender)
  ## remove NAs from actual
  keep = !is.na(md$gdc_cases.demographic.gender)
  actual = actual_all[keep]
  #define predicted
  predicted = predictions[keep]



  #summarize data
  number_match <- sum(predicted==actual)
  perc_correct = sum(predicted==actual)/length(actual)
  number_sites = nrow(predictor$coefEsts)

  TCGA_summarized = as.data.frame(cbind(number_sites,number_match, perc_correct))
  names(TCGA_summarized) <- c("sites_tested", "number_correct", "percent_correct")
 
 #compare predictions to known sex
 TCGA_summarized

 #get output for package
predictions_tcga = as.data.frame(cbind(md$gdc_file_id,"tcga",actual=actual_all,predicted=predictions,perc_correct))
```



```{r 'extract-sra-data', message = FALSE, warning = FALSE}
library(GenomicRanges)
if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/merge_input_Sex_nocovars.rda")){
  #### SRA data [generated in merge_bwtool_by_chunk.R]
  ## which chunk regions are in [chunk_grp]
  load('/dcl01/leek/data/sellis/barcoding/data/chunk_grp.Rdata')
  ## region information [regions]
  load('/dcl01/leek/data/sellis/barcoding/data/regions-cut0.5.Rdata')
  reg = regions
  rm(regions)
  ## add chunk information to all 1,187,643 regions
  reg$chunkname <- chunk_grp

  ## GTEx regions to subset
  regions_to_subset = predictor$regiondata

  ## get regions overlap [b/w all quantified regions and GTEx subset]
  ov <- findOverlaps(reg,regions_to_subset)
  ## Integer vector to re-order regions to https://github.com/jtleek/sra-gtex/blob/master/select-gtex-ers.R#L80-L88
  index_regions <- subjectHits(ov)
  index_regions_query <- queryHits(ov)
  #reorder GRanges objects
  reg <- reg[index_regions_query,]
  regions_to_subset <- regions_to_subset[index_regions,]

  regions_split <- split(reg, reg$chunkname)


  ## load the coverageMatrix of interest from the appropriate "chunk"

  # dir.create('data/coverageMatrix_subset', showWarnings = FALSE)

  xx <- mapply(function(regs, chunk_name) {
      message(paste(Sys.time(), 'processing', chunk_name))
      
      ## Load coverage matrix for each chunk [coverageMatrix]
      load(paste0('/dcl01/leek/data/gtex_work/runs/sra/DER_analysis/coverageMatrix/ers_gtex/coverageMatrix-cut0.5-', chunk_name, '.Rdata'))

      ## Load regions included in the chunk [regions_subset]
     load( paste0('/dcl01/leek/data/gtex_work/runs/sra/DER_analysis/coverageMatrix/ers_gtex/regions_', chunk_name, '-cut0.5.Rdata'))

      ## Identify which regions to keep
      regions_keep <- which(countOverlaps( regions_subset,regions_to_subset) > 0)
      stopifnot(length(regions_keep) == length(regs))
      
      ## Save actual subset of regions used
      regions_subset <- regions_subset[regions_keep]
      save(regions_subset, file = paste0('/dcl01/leek/data/sellis/barcoding/data/minfi_rda/regions_', chunk_name, '-cut0.5.Rdata'))
      
      ## Compute chunk coverage matrix
      coverageMatrix_subset <- coverageMatrix[regions_keep,]
      save(coverageMatrix_subset, file = paste0('/dcl01/leek/data/sellis/barcoding/data/minfi_rda/coverageMatrix-cut0.5-', chunk_name,
          '.Rdata'))
      
      ## Finish
      return(invisible(NULL))
  }, regions_split, names(table(reg$chunkname)))

  ## compile the subset of regions into a single object
  chunks <-names(table(reg$chunkname))
  coverageMatrix=c()
  regions = GRanges()

  for (i in 1:length(chunks)){
        message(paste(Sys.time(), 'processing', chunks[i]))

    ## load in each chunk and save to a data frame
    load(paste0('/dcl01/leek/data/sellis/barcoding/data/minfi_rda/coverageMatrix-cut0.5-', chunks[i],
          '.Rdata'))
    coverageMatrix = rbind(coverageMatrix, coverageMatrix_subset)

    ## load in and combine region data
    load(paste0('/dcl01/leek/data/sellis/barcoding/data/minfi_rda/regions_', chunks[i], '-cut0.5.Rdata'))
    regions = append(regions,regions_subset)
  } 

  sra_inputdata = list(covmat=coverageMatrix,regiondata=regions)

  save(sra_inputdata,file='/dcl01/leek/data/sellis/barcoding/data/SRA_inputdata_Sex.Rdata')
}else{
  load('/dcl01/leek/data/sellis/barcoding/data/SRA_inputdata_Sex.Rdata')
}

```

# Predict phenotype in SRA

```{r 'predict-SRA', message = FALSE, warning = FALSE}
#get inputdata in order
ov <- findOverlaps(predictor$regiondata,sra_inputdata$regiondata)
index_regions <- subjectHits(ov)
#reorder GRanges objects
sra_inputdata$regiondata <- sra_inputdata$regiondata[index_regions]
sra_inputdata$covmat <- log2(sra_inputdata$covmat[index_regions,]+1)

predictions<-predict_pheno(inputdata_test= sra_inputdata, phenodata=pheno, phenotype="Sex", covariates=NULL,type="factor", predictordata = predictor)
# number of samples
length(predictions)

  #since we know the truth here, let's check and see how we're doing:
 
## load SRA metadata
### Load in SRA metadata
load('/dcl01/leek/data/recount-website/metadata/metadata_sra.Rdata')
metadata <- metadata[!is.na(metadata$bigwig_path), ]
sra_meta = metadata
rm(metadata)


### Keep only the good SRA and get them in the same order
mm = match(colnames(sra_inputdata$covmat),sra_meta$run)
sra_meta = sra_meta[mm,]
pd = read_csv("https://raw.githubusercontent.com/nellore/runs/master/sra/v2/hg38/SraRunInfo.csv")
sra_meta = left_join(as.data.frame(sra_meta),pd,by=c("run"="Run","sample"="Sample"))

 #pull out actual Sex
  actual_all = sra_meta$Sex
  actual = sra_meta$Sex

  #define predicted
  predicted = predictions

  ## only compare between those annotated in SRA 
  sexes = c("F","female","Female","M","male","Male")
  actual_subset = actual[actual %in% sexes]
  actual_subset[actual_subset=="Female"] <- "female"
  actual_subset[actual_subset=="F"] <- "female"
  actual_subset[actual_subset=="Male"] <- "male"
  actual_subset[actual_subset=="M"] <- "male"

  predicted_subset = predicted[actual %in% sexes]
  length(predicted_subset)

  #summarize data
  number_match <- sum(predicted_subset==actual_subset)
  perc_correct = sum(predicted_subset==actual_subset)/length(actual_subset)
  number_sites = nrow(predictor$coefEsts)

  SRA_summarized = c(number_sites,number_match, perc_correct)
  names(SRA_summarized) <- c("sites_tested", "number_correct", "percent_correct")
 
 #compare predictions to known sex
 SRA_summarized

  #get output for package
predictions_sra =  as.data.frame(cbind(sra_meta$run,"sra",actual=as.character(actual_all),predicted=predicted,perc_correct))

```

```{r 'plot-output', message = FALSE, warning = FALSE,fig.width=8}

data = rbind(predictions_test$summarized,summarized,TCGA_summarized,SRA_summarized) %>% data.frame()
t(data) %>% as.matrix() -> mat
colnames(mat) <- c("GTEx: training","GTEx: test","TCGA", "SRA")
mat 

colours2 = c(bright["purple"],bright["purple"],bright["pink"],bright["teal"])

 # library(extrafont)
 # pdf("/dcl01/leek/data/sellis/barcoding/plots/SexPrediction.pdf",family="Roboto Condensed",width=12, height=6)
par(cex=1.3)
barplot(as.numeric(mat["percent_correct",]*100), names.arg=c("GTEx: training","GTEx: test","TCGA", "SRA"),
        main="Sex", ylim=c(0,100), ylab="Accuracy", xlab="Data Set Used", col=colours2, cex.lab=1.3, cex.axis=1.2, cex.main=1.4)
axis(1, at=c(0,5), xpd=T, lwd.ticks = 0, labels=F)
#dev.off() 
```

```{r 'pheno-output', message = FALSE, warning = FALSE}
predictions_Sex <- rbind(predictions_gtex,predictions_gtex_test,predictions_tcga,predictions_sra)
colnames(predictions_Sex) <- c("sample_id","dataset","reported_sex","predicted_sex","accuracy_sex") 
predictions_Sex$dataset <- factor(predictions_Sex$dataset)
predictions_Sex$reported_sex <- factor(predictions_Sex$reported_sex)
predictions_Sex$predicted_sex <- factor(predictions_Sex$predicted_sex)
predictions_Sex$accuracy_sex <- as.numeric(predictions_Sex$accuracy_sex)

save(predictions_Sex, file="/dcl01/leek/data/sellis/barcoding/output/predictions_Sex.rda")
```

```{r 'region-information', message = FALSE, warning = FALSE}
## Get required information for the plots
if(!file.exists("/dcl01/leek/data/sellis/barcoding/output/Sex_regions.rda")){
library(bumphunter)
txdb <- makeTxDbFromGFF('ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.annotation.gff3.gz', format = 'gff3', organism = 'Homo sapiens')
tx<-annotateTranscripts(txdb)
annotation <- matchGenes(x = predictor$regiondata, subject = tx)

table(annotation$description)
table(seqnames(predictor$regiondata))
save(annotation, file= "/dcl01/leek/data/sellis/barcoding/output/Sex_regions.rda")
}else{
  load("/dcl01/leek/data/sellis/barcoding/output/Sex_regions.rda")
}
table(output$description)
```

# Vignette information

```{r reproducibility}
## Time spent creating this report:
diff(c(startTime, Sys.time()))

## Date this report was generated
message(Sys.time())

## Reproducibility info
options(width = 120)
devtools::session_info()
```

Code for creating the vignette

```{r createVignette, eval=FALSE}
## Create the vignette
library('rmarkdown')
system.time(render('/dcl01/leek/data/sellis/barcoding/phenotype_vignettes/phenopredict-Sex.Rmd', 'BiocStyle::html_document'))

## Extract the R code
library('knitr')
knit('/dcl01/leek/data/sellis/barcoding/phenotype_vignettes/phenopredict-Sex.Rmd', tangle = TRUE)
```





