---
title: "Sequencing Strategy Prediction"
author: "Shannon E. Ellis"
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{recount quick start guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r vignetteSetup, echo=FALSE, message=FALSE, warning = FALSE}
## Track time spent on making the vignette
startTime <- Sys.time()
```
# Load libraries

```{r load-packages, message = FALSE, warning = FALSE}
## load libraries
library(devtools)
# install_github("leekgroup/phenopredict")
document("/users/sellis/phenopredict")
library('phenopredict')
library(rtracklayer)
library(recount)
library(genefilter)
library(plyr)
library(GenomicRanges)


## Set colors
## import colors to use
  bright= c(red=rgb(222,45,38, maxColorValue=255), #de2d26
            pink=rgb( 255, 102, 153, maxColorValue=255), #ff6699
            orange=rgb(232,121,12, maxColorValue=255),   #e8790c
            yellow=rgb(255,222,13, maxColorValue=255), #ffde0d          
            green=rgb(12,189,24, maxColorValue=255),  #0cbd18           
            teal=rgb(59,196,199, maxColorValue=255), #3bc4c7
            blue=rgb(58,158,234, maxColorValue=255), #3a9eea
            purple=rgb(148,12,232, maxColorValue=255)) #940ce8  
```

# Load SRA metadata
```{r 'load-sra-metadata', message = FALSE, warning = FALSE}

## load SRA metadata
### Load in SRA metadata
   #### SRA data [generated in merge_bwtool_by_chunk.R]
  ## which chunk regions are in [chunk_grp]
  load('/dcl01/leek/data/sellis/barcoding/data/chunk_grp.Rdata')
  ## region information [regions]
  load('/dcl01/leek/data/sellis/barcoding/data/regions-cut0.5.Rdata')
  reg = regions
  rm(regions)
  ## add chunk information to all 1,187,643 regions
  reg$chunkname <- chunk_grp

    ## have to go through and select regions from each chunk that specify library prep
	regions_split <- split(reg, reg$chunkname)
	phenot="LibraryLayout"

  ## remove noncanoncial chromosomes
  chunk_name = table(chunk_grp) %>% names()
  chunk_name = grep("chrUn", chunk_name,invert=T,val=T)
  chunk_name = grep("random", chunk_name,invert=T,val=T)
  chunk_name = grep("EBV", chunk_name,invert=T,val=T)
  chunk_name = grep("chrM", chunk_name,invert=T,val=T)

 # selecting training and test set samples
 load(paste0('/dcl01/leek/data/gtex_work/runs/sra/DER_analysis/coverageMatrix/ers_gtex/coverageMatrix-cut0.5-', chunk_name[1], '.Rdata'))
  set.seed(1567)
  samples_to_use<-sample(colnames(coverageMatrix), ncol(coverageMatrix)/2 )
  keep = colnames(coverageMatrix) %in% samples_to_use

load('/dcl01/leek/data/recount-website/metadata/metadata_sra.Rdata')
metadata <- metadata[!is.na(metadata$bigwig_path), ]
sra_meta = metadata
rm(metadata)


### Keep only the good SRA and get them in the same order
mm = match(colnames(coverageMatrix),sra_meta$run)
sra_meta = sra_meta[mm,]
pd = read_csv("https://raw.githubusercontent.com/nellore/runs/master/sra/v2/hg38/SraRunInfo.csv")
sra_meta = left_join(as.data.frame(sra_meta),pd,by=c("run"="Run","sample"="Sample"))

 sra_meta_training <<- sra_meta[keep,]
 sra_meta_test <<- sra_meta[!keep,]
```

# Filter regions from training data

```{r 'filter-regions', message = FALSE, warning = FALSE}
if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/SRA_inputdata_SequencingStrategy.Rdata")){

	xx <- lapply(chunk_name, function(chunk_name) {
	     message(paste(Sys.time(), 'processing', chunk_name))
	      
	     ## Load coverage matrix for each chunk [coverageMatrix]
	     load(paste0('/dcl01/leek/data/gtex_work/runs/sra/DER_analysis/coverageMatrix/ers_gtex/coverageMatrix-cut0.5-', chunk_name, '.Rdata'))

	      ## Load regions included in the chunk [regions_subset]
	     load(paste0('/dcl01/leek/data/gtex_work/runs/sra/DER_analysis/coverageMatrix/ers_gtex/regions_', chunk_name, '-cut0.5.Rdata'))

	     ## split into training and test 
	     sra_training = coverageMatrix[,keep]
	     sra_test = coverageMatrix[,!keep]



	     ## quick and dirty test to minimize number of regions input 
	     if(length(names(table(sra_meta_training[,phenot])))==2){
	     	subs = rowttests(sra_training,factor(sra_meta_training[,phenot]))
	     }else(
	     	subs = rowftests(sra_training,factor(sra_meta_training[,phenot]))
	     )

	     cutoff = quantile(subs$p.value,0.05)
	     tokeep<-subs$p.value<cutoff
	    sra_training = log2(sra_training[tokeep,]+1)
	    sra_test = log2(sra_test[tokeep,]+1)
		regions_subset = regions_subset[tokeep]

	      ## Select regions associated with LibraryPrep
   		 inputdata<-filter_regions(expression=sra_training, regiondata=regions_subset ,phenodata=sra_meta_training, phenotype=phenot, covariates=NULL,type="factor", numRegions=10)

   		new<-extract_data(newexpression=sra_test, newregiondata=regions_subset, predictordata=inputdata)
    	inputdata$sra_test <- new
	     
	      ## Finish
	      return(inputdata)
	  })
	names(xx) <- chunk_name

	  ## compile the subset of regions into a single object
	  merge_input<- merge_input(inputdata_list=xx)

	#remove "id"column
	merge_input$covmat = dplyr::select(merge_input$covmat, -(.id))
    ## so that I never have to run this chunk again
    save(xx, file='/dcl01/leek/data/sellis/barcoding/data/SRA_fulldata_SequencingStrategy.Rdata')
    ## so that I have what I need
	  save(merge_input,file='/dcl01/leek/data/sellis/barcoding/data/SRA_inputdata_SequencingStrategy.Rdata')
	}else{
	  load('/dcl01/leek/data/sellis/barcoding/data/SRA_inputdata_SequencingStrategy.Rdata')
	}

# taking a look at output of filter_regions)
dim(merge_input$covmat)
merge_input$regiondata

```


# Build predictor in SRA training data

```{r 'build-predictor', message = FALSE, warning = FALSE}
if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/build_predictor_SequencingStrategy_nocovars.rda")) {
	predictor<-build_predictor(inputdata=merge_input ,phenodata=sra_meta_training, phenotype=phenot,		 
		covariates=NULL,type="factor", numRegions=20)
	save(predictor, file= "/dcl01/leek/data/sellis/barcoding/data/build_predictor_SequencingStrategy_nocovars.rda")
}else{
	load('/dcl01/leek/data/sellis/barcoding/data/build_predictor_SequencingStrategy_nocovars.rda')
}

#number of probes used for prediction
length(predictor$trainingProbes)

#this contains the coefficient estimates used for prediction. 
# the number of rows corresponds to the number of sites used for prediction
# while the columns corresponds to the number of categories of your phenotype.
dim(predictor$coefEsts)
```

# Resubstitution Error (in SRA training data)

```{r 'test-predictor', message = FALSE, warning = FALSE}
predictions_test <-test_predictor(inputdata=merge_input ,phenodata=sra_meta_training, phenotype=phenot, 
    covariates=NULL,type="factor",predictordata=predictor )
# number of samples
length(predictions_test$predicted)

# get summary of how prediction is doing
predictions_test$summarized

summarized_training = predictions_test$summarized

predicted = predictions_test$predicted
actual = sra_meta_training[,phenot]

perc_correct = as.numeric(sum(predicted==actual)/length(actual))

 #get output for package
predictions_SequencingStrategy = data.frame(cbind(sra_meta_training$run,"sra",actual=as.character(actual),predicted=predicted,perc_correct))


## how do predictions fare when sra_misreported_paired_end==TRUE
set <- actual!=predicted
mismatch = sra_meta_training$sra_misreported_paired_end[set]
table(sra_meta_training$sra_misreported_paired_end)

table(mismatch)
#Proportion of samples with misreported paired end sequencing that are 'incorrect' predictions in SRA training data
length(mismatch[mismatch==TRUE])/length(sra_meta_training$sra_misreported_paired_end[sra_meta_training$sra_misreported_paired_end==TRUE])

## Percent correct, accounting for mismatch samples
sum(predicted==actual)+length(mismatch[mismatch==TRUE])
length(actual)
(perc_correct_adjusted = as.numeric((sum(predicted==actual)+length(mismatch[mismatch==TRUE]))/length(actual)))


# how many different projects do these come from?
projnum = sra_meta_training[set,]
projnum = projnum[mismatch==TRUE,]
length(unique(projnum$project))
length(unique(projnum$project))/length(unique(sra_meta_training$project))
```

# Extract data for SRA test set

```{r 'extract-data', message = FALSE, warning = FALSE}
# looking at the input data for extract_data
if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/sra_test_inputdata_SequencingStrategy_nocovars.rda")) {

	purrr::map(xx, function(x){return(x$sra_test)}) %>% ldply(., data.frame) -> sra_test_covmat
	#remove "id"column
	sra_test_covmat= dplyr::select(sra_test_covmat, -(.id))

	colremove<-grep("regiondata", colnames(sra_test_covmat))
  sra_test_regiondata= sra_test_covmat[, colremove]
  identical(sra_test_regiondata$regiondata.width, width(merge_input$regiondata))
  ## can just use merge_input$regiondata as regiondata object
	sra_test_covmat= sra_test_covmat[, -colremove]

	  sra_test_inputdata=list()
	  ov <- findOverlaps(predictor$regiondata,merge_input$regiondata)
	  index_regions <- subjectHits(ov)
	  #reorder GRanges objects
	  sra_test_inputdata$covmat  <- sra_test_covmat[index_regions,]
	  sra_test_inputdata$regiondata <- merge_input$regiondata[index_regions]

	save(sra_test_inputdata, file= "/dcl01/leek/data/sellis/barcoding/data/sra_test_inputdata_SequencingStrategy_nocovars.rda")
}else{
	load('/dcl01/leek/data/sellis/barcoding/data/sra_test_inputdata_SequencingStrategy_nocovars.rda')
}
```

# Predict Sequencing Strategy in SRA test set

```{r 'predict-phenotype', message = FALSE, warning = FALSE}
predictions<-predict_pheno(inputdata_test= sra_test_inputdata, phenodata=sra_meta_test, phenotype=phenot, covariates=NULL,type="factor", predictordata = predictor)
# number of samples
length(predictions)

#since we know the truth here, let's check and see how we're doing:
 
  actual = sra_meta_test[,phenot]

  #define predicted
  predicted = predictions

  #summarize data
	number_match <- sum(predicted==actual)
	perc_correct = sum(predicted==actual)/length(actual)
	number_sites = nrow(predictor$coefEsts)

	summarized = cbind(number_sites,number_match, perc_correct)
	colnames(summarized) <- c("sites_tested", "number_correct", "percent_correct")
 
 #compare predictions to known sex
 summarized


#get output for package
predictions_SequencingStrategy_test = as.data.frame(cbind(sra_meta_test$run,"sra",actual=as.character(actual),predicted,perc_correct))
#update training set with test set perc_correct
predictions_SequencingStrategy$perc_correct <- perc_correct

## how do predictions fare when sra_misreported_paired_end==TRUE
set <- actual!=predicted
table(sra_meta_test$sra_misreported_paired_end)
mismatch = sra_meta_test$sra_misreported_paired_end[set]
table(mismatch)
#Proportion of samples with misreported paired end sequencing that are 'incorrect' predictions in SRA training data
length(mismatch[mismatch==TRUE])/length(sra_meta_test$sra_misreported_paired_end[sra_meta_test$sra_misreported_paired_end==TRUE])


## Percent correct, accounting for mismatch samples
sum(predicted==actual)+length(mismatch[mismatch==TRUE])
length(actual)
(perc_correct_adjusted = as.numeric((sum(predicted==actual)+length(mismatch[mismatch==TRUE]))/length(actual)))


# how many different projects do these come from?
projnum = sra_meta_test[set,]
projnum = projnum[mismatch==TRUE,]
length(unique(projnum$project))
length(unique(projnum$project))/length(unique(sra_meta_test$project))

```

# Predict Sequnencing Strategy in TCGA
```{r 'predict-phenotype-tcga', message = FALSE, warning = FALSE}

regions = predictor$regiondata

# get phenotype info in order
recount::all_metadata('TCGA') -> md 
bws = gsub('.bw','', md$bigwig_file)

if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/TCGA_SeqStrat_inputdata.rda")) {

  ## Extract same regions from TCGA data
  load('/dcl01/lieber/ajaffe/lab/gtex_ers/rse_TCGA.Rdata')
  findOverlaps(regions,rse) -> ov
  ## extract regions from predictor
  rse[subjectHits(ov)] -> rse_sub
  ## get coverage matrix ; order same as in regions
  ## note: these aren't scaled
  cov_tcga <- assays(rse_sub)$counts




  #ensure covmat is in same order as regions
  if( identical(tolower(bws),colnames(cov_tcga))==TRUE){
    covmat= cov_tcga
    regions = regions

    #remove coverage samples for which we don't have metadata
    covmat = covmat[,colnames(covmat) %in% tolower(bws)]

    #put data on a log2 scale
    dm = log2(covmat+1)
    md2 = md 
  }else{
    message("metadata and expression data not in same order")
  }

  tcga_meta2 = md2


  TCGA_inputdata=c()
  TCGA_inputdata$covmat <- dm
  TCGA_inputdata$regiondata <- predictor$regiondata

    ov <- findOverlaps(predictor$regiondata,TCGA_inputdata$regiondata)
    index_regions <- subjectHits(ov)
    #reorder GRanges objects
    TCGA_inputdata$regiondata <- TCGA_inputdata$regiondata[index_regions]
    TCGA_inputdata$covmat <- TCGA_inputdata$covmat[index_regions,]

    save(TCGA_inputdata, tcga_meta2, file="/dcl01/leek/data/sellis/barcoding/data/TCGA_SeqStrat_inputdata.rda")
}else{
  load("/dcl01/leek/data/sellis/barcoding/data/TCGA_SeqStrat_inputdata.rda")
}


  predictions_tcga<-predict_pheno(inputdata_test= TCGA_inputdata, phenodata=sra_meta_training, phenotype=phenot, covariates=NULL,type="factor", predictordata = predictor)

  # number of samples
  length(predictions_tcga)

  actual_all =  rep(c("PAIRED"),length(predictions_tcga))
  ## remove NAs from actual
  keep = !is.na(predictions_tcga)
  actual = actual_all[keep]
  #define predicted
  predicted = predictions_tcga[keep]



  #summarize data
  number_match <- sum(predicted==actual)
  perc_correct = sum(predicted==actual)/length(actual)
  number_sites = nrow(predictor$coefEsts)

  TCGA_summarized = as.data.frame(cbind(number_sites,number_match, perc_correct))
  names(TCGA_summarized) <- c("sites_tested", "number_correct", "percent_correct")
 
 #compare predictions to known sex
 TCGA_summarized

 #get output for package
predictions_tcga = as.data.frame(cbind(md$gdc_file_id,"tcga",actual=actual_all,predicted=predictions_tcga,perc_correct))

summarized_tcga = cbind(number_sites,number_match, perc_correct)
colnames(summarized_tcga) <- c("sites_tested", "number_correct", "percent_correct")

```

# Predict Library Type in GTEx

```{r 'predict-phenotype-gtex', message = FALSE, warning = FALSE}
#get GTEx metadata
load("/dcl01/leek/data/sellis/barcoding/data/sample_individuals.Rdata")
load("/dcl01/leek/data/sellis/barcoding/data/rda/gtexmetadata.rda")
gtex_meta = gtexmetadata
gtex_meta = cbind(gtex_meta,usegtex)
rm(gtexmetadata,usegtex)
gtex_meta[is.na(gtex_meta[,"SMTS"]),"SMTS"] <- c("Esophagus","Skin","Stomach","Skin","Esophagus")
usegtex = gtex_meta$usegtex
pheno = gtex_meta
pheno = pheno[usegtex,]

if(!file.exists("/dcl01/leek/data/sellis/barcoding/data/GTEx_inputdata_sequencingstrategy.rda")) {
## Get GTEx data
  source("/dcl01/leek/data/sellis/barcoding/scripts/gtexLoad.R")

  chrs = c("X","Y",1:22)
  i=1
  chrname=paste0("chr",chrs[i])
    cat(paste0(chrname,"..."))
    dat = gtexLoad(chrname)
    cm = dat$coverageMatrix
    regiondata = dat$regions
    cm = log2(cm + 1)
    wid = width(dat$regions)
    cm = cm[, usegtex]

    gtex_inputdata = list()
    ov <- findOverlaps(predictor$regiondata,regiondata)
    index_regions <- subjectHits(ov)
    #reorder GRanges objects
    gtex_inputdata$regiondata <- regiondata[index_regions]
    gtex_inputdata$covmat <- cm[index_regions,]

  for(i in 2:length(chrs)){
    chrname=paste0("chr",chrs[i])
    cat(paste0(chrname,"..."))
    dat = gtexLoad(chrname)
    cm = dat$coverageMatrix
    regiondata = dat$regions
    cm = log2(cm + 1)
    wid = width(dat$regions)
    cm = cm[, usegtex]

    ov <- findOverlaps(predictor$regiondata,regiondata)
    index_regions <- subjectHits(ov)
    #reorder GRanges objects
    gtex_inputdata$regiondata <- c(gtex_inputdata$regiondata,regiondata[index_regions])
    gtex_inputdata$covmat <- rbind(gtex_inputdata$covmat,cm[index_regions,])  
  }

  ov <- findOverlaps(predictor$regiondata,gtex_inputdata$regiondata)
    index_regions <- subjectHits(ov)
    #reorder GRanges objects
    gtex_inputdata$regiondata <- gtex_inputdata$regiondata[index_regions]
    gtex_inputdata$covmat <- gtex_inputdata$covmat[index_regions,] 
    gtex_inputdata$regiondata <- predictor$regiondata


  save(gtex_inputdata, file="/dcl01/leek/data/sellis/barcoding/data/GTEx_inputdata_sequencingstrategy.rda")
}else{
  load("/dcl01/leek/data/sellis/barcoding/data/GTEx_inputdata_sequencingstrategy.rda")
}


predictions_gtex<-predict_pheno(inputdata_test= gtex_inputdata, phenodata=pheno, phenotype=phenot, covariates=NULL,type="factor", predictordata = predictor)
# number of samples
length(predictions_gtex)

#since we know the truth here, let's check and see how we're doing:
  actual = rep("PAIRED",length(predictions_gtex))

  #define predicted
  predicted = predictions_gtex

  #summarize data
	number_match <- sum(predicted==actual)
	perc_correct = sum(predicted==actual)/length(actual)
	number_sites = nrow(predictor$coefEsts)

	summarized_gtex = cbind(number_sites,number_match, perc_correct)
	colnames(summarized_gtex) <- c("sites_tested", "number_correct", "percent_correct")
 
 #compare predictions to known sex
 summarized_gtex

 #get output for package
predictions_gtex = as.data.frame(cbind(pheno$Run,"gtex",actual,predicted,perc_correct))
```

```{r 'plot-output', message = FALSE, warning = FALSE}

data = rbind(summarized_training,summarized,summarized_gtex,summarized_tcga) %>% data.frame()
t(data) %>% as.matrix() -> mat
colnames(mat) <- c("SRA: training","SRA: test","GTEx", "TCGA")
mat 

colours2 = c(bright["teal"],bright["teal"],bright["purple"],bright["pink"])

# library(extrafont)
# pdf("/dcl01/leek/data/sellis/barcoding/plots/SequencingStrategyPrediction.pdf",family="Roboto Condensed",width=12, height=6)
par(cex=1.3)
barplot(as.numeric(mat["percent_correct",])*100, names.arg=c("SRA: training","SRA: test","GTEx","TCGA"),
        main="Sequencing Strategy", ylim=c(0,100), ylab="Accuracy", xlab="Data Set Used", col=colours2, cex.lab=1.3, cex.axis=1.2, cex.main=1.4)
axis(1, at=c(0,5), xpd=T, lwd.ticks = 0, labels=F)
# dev.off()

```

```{r 'pheno-output', message = FALSE, warning = FALSE}
predictions_SequencingStrategy <- rbind(predictions_SequencingStrategy,predictions_SequencingStrategy_test,predictions_gtex,predictions_tcga)
colnames(predictions_SequencingStrategy) <- c("sample_id","dataset","reported_sequencingstrategy","predicted_sequencingstrategy","accuracy_sequencingstrategy") 

predictions_SequencingStrategy$dataset <- factor(predictions_SequencingStrategy$dataset)
predictions_SequencingStrategy$reported_sequencingstrategy <- factor(predictions_SequencingStrategy$reported_sequencingstrategy)
predictions_SequencingStrategy$predicted_sequencingstrategy <- factor(predictions_SequencingStrategy$predicted_sequencingstrategy)
predictions_SequencingStrategy$accuracy_sequencingstrategy <- as.numeric(predictions_SequencingStrategy$accuracy_sequencingstrategy)

save(predictions_SequencingStrategy, file="/dcl01/leek/data/sellis/barcoding/output/predictions_SequencingStrategy.rda")
```


```{r 'region-information', message = FALSE, warning = FALSE}
## Get required information for the plots
# if(!file.exists("/dcl01/leek/data/sellis/barcoding/output/SequencingStrategy_regions.rda")) {
# 	library(minfi)
#   txdb <- GenomicFeatures::makeTxDbFromGFF('ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.annotation.gff3.gz', format = 'gff3', organism = 'Homo sapiens')
# 	tx<-annotateTranscripts(txdb, annotationPackage = NULL, by = c("tx","gene"), codingOnly=FALSE, verbose = TRUE, requireAnnotation = FALSE)
# 	output<-matchGenes(predictor$regiondata, tx, type = c("any", "fiveprime"), promoterDist = 2500, skipExons = FALSE, verbose = TRUE)
# 	table(output$description)
# 	save(output, file= "/dcl01/leek/data/sellis/barcoding/output/SequencingStrategy_regions.rda")
# }else{
# 	load("/dcl01/leek/data/sellis/barcoding/output/SequencingStrategy_regions.rda")
# 	table(output$description)
# }
```

# Vignette information

```{r reproducibility}
## Time spent creating this report:
diff(c(startTime, Sys.time()))

## Date this report was generated
message(Sys.time())

## Reproducibility info
options(width = 120)
devtools::session_info()
```

Code for creating the vignette

```{r createVignette, eval=FALSE}
## Create the vignette
library('rmarkdown')
system.time(render('/dcl01/leek/data/sellis/barcoding/phenotype_vignettes/phenopredict-SequencingStrategy.Rmd', 'BiocStyle::html_document'))

## Extract the R code
library('knitr')
knit('/dcl01/leek/data/sellis/barcoding/phenotype_vignettes/phenopredict-SequencingStrategy.Rmd', tangle = TRUE)
```


