---
title: "Graphical Prediction Summary"
author: "Shannon E. Ellis"
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{recount quick start guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r vignetteSetup, echo=FALSE, message=FALSE, warning = FALSE}
## Track time spent on making the vignette
startTime <- Sys.time()

## load colors
  bright= c(red=rgb(222,45,38, maxColorValue=255), #de2d26
            pink=rgb( 255, 102, 153, maxColorValue=255), #ff6699
            orange=rgb(232,121,12, maxColorValue=255),   #e8790c
            yellow=rgb(255,222,13, maxColorValue=255), #ffde0d          
            green=rgb(12,189,24, maxColorValue=255),  #0cbd18           
            teal=rgb(59,196,199, maxColorValue=255), #3bc4c7
            blue=rgb(58,158,234, maxColorValue=255), #3a9eea
            purple=rgb(148,12,232, maxColorValue=255)) #940ce8 
```

# Load Data

```{r load-data, message=FALSE, warning = FALSE}
load('/dcl01/leek/data/sellis/barcoding/output/PredictedPhenotypes_v0.0.04.rda')

df = PredictedPhenotypes

## Get it in order
df$dataset = factor(df$dataset,levels(df$dataset)[c(1,3,2)])

## Summarize each phenotype
(dataset_summ <- df %>%  group_by(dataset) %>% select(dataset) %>% summarise(Count = n()))
(sex_summ <- df %>%  group_by(dataset,predicted_sex) %>% select(predicted_sex) %>% summarise(Count = n())) 
(tissue_summ <- df %>%  group_by(dataset,predicted_tissue) %>% select(predicted_tissue) %>% summarise(Count = n()))
(strategy_summ <- df %>%  group_by(dataset,predicted_sequencingstrategy) %>% select(predicted_sequencingstrategy) %>% summarise(Count = n()))
(source_summ <- df %>%  group_by(dataset,predicted_samplesource) %>% select(predicted_samplesource) %>% summarise(Count = n()))
```
# Plot Data Summaries

```{r plot-data, echo=FALSE, message=FALSE, warning = FALSE, fig.width=9, fig.height=4}

## Data set sample size
ggplot(data = dataset_summ, aes(x=dataset, y = Count,label = Count)) + 
	labs(y="No. of Samples",x="Data Set",title="Sample Summary") +
    geom_bar(stat="identity", aes(fill = dataset),position="dodge") +
    geom_text(size = 6, position = position_stack(),colour="black") +
    scale_fill_manual(values=c("#940CE8", "#FF6699", "#3BC4C7"))+
    theme_bw()+
    theme(legend.title=element_blank(),plot.title = element_text(hjust = 0.5),text = element_text(size=20), panel.border = element_blank(), panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"))

## Sex
ggplot(data = sex_summ, aes(x=dataset, y = Count,label = Count)) + 
	labs(y="No. of Samples",x="Data Set",title="Predicted Sex") +
    geom_bar(stat="identity", aes(fill = predicted_sex),position="dodge") +
    geom_text(aes(fill=predicted_sex),size = 6, position = position_dodge(width = 0.9),colour="black") +
    scale_fill_manual(values=c("#940CE8", "#0CBD18", "grey48"))+
    theme_bw()+
    theme(legend.title=element_blank(),plot.title = element_text(hjust = 0.5),text = element_text(size=20), panel.border = element_blank(), panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"))

## Sequencing Strategy
ggplot(data = strategy_summ, aes(x=dataset, y = Count,label = Count)) + 
	labs(y="No. of Samples",x="Data Set",title="Predicted Sequencing Strategy") +
    geom_bar(stat="identity", aes(fill = predicted_sequencingstrategy),position="dodge") +
    geom_text(aes(fill=predicted_sequencingstrategy),size = 6, position = position_dodge(width = 0.9),colour="black") +
	scale_fill_manual(values=c("#E8790C", "#3A9EEA", "grey48"))+
    theme_bw()+
    theme(legend.title=element_blank(),plot.title = element_text(hjust = 0.5),text = element_text(size=20), panel.border = element_blank(), panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"))

## Sample Source 
ggplot(data = source_summ, aes(x=dataset, y = Count,label = Count)) + 
	labs(y="No. of Samples",x="Data Set",title="Predicted Sample Source") +
    geom_bar(stat="identity", aes(fill = predicted_samplesource),position="dodge") +
    geom_text(aes(fill=predicted_samplesource),size = 6, position = position_dodge(width = 0.9),colour="black") +
    scale_fill_manual(values=c("#3BC4C7", "#DE2D26", "grey48"))+
    theme_bw()+
    theme(legend.title=element_blank(),plot.title = element_text(hjust = 0.5),text = element_text(size=20), panel.border = element_blank(), panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"))

## Tissue
ggplot(data = tissue_summ, aes(x=predicted_tissue,y = Count,label = Count)) + 
	labs(y="No. of Samples",x="Data Set",title="Predicted Tissue") +
    geom_bar(stat="identity", aes(fill = predicted_tissue),position="dodge") +
    facet_wrap(~dataset,ncol=3,scales="free_y")+
    theme_bw()+
    theme(legend.title=element_blank(),plot.title = element_text(hjust = 0.5),text = element_text(size=20), panel.border = element_blank(), panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"),axis.text.x=element_blank(), axis.ticks.x=element_blank())

```

# Secondary Analyses

```{r sex-discordance, echo=FALSE, message=FALSE, warning = FALSE, fig.width=9, fig.height=4}

### taking a look at reported sex across datasets
df$reported_sex[df$reported_sex=="Male"]<-"male"
df$reported_sex[df$reported_sex=="M"]<-"male"
df$reported_sex[df$reported_sex=="Female"]<-"female"
df$reported_sex[df$reported_sex=="F"]<-"female"
sexes = c("male","female")
df$reported_sex[(!df$reported_sex %in% sexes)] <- NA
df$reported_sex <- droplevels(df$reported_sex)

(test <- df %>%  group_by(dataset,reported_sex) %>% select(reported_sex) %>% summarise(Count = n())) 


ggplot(data = test, aes(x=dataset, y = Count,label = Count)) + 
	labs(y="No. of Samples",x="Data Set",title="Reported Sex") +
    geom_bar(stat="identity", aes(fill = reported_sex),position="dodge") +
    geom_text(aes(fill=reported_sex),size = 6, position = position_dodge(width = 0.9),colour="black") +
    theme_bw()+
    theme(legend.title=element_blank(),plot.title = element_text(hjust = 0.5),text = element_text(size=20), panel.border = element_blank(), panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text=element_text(colour="black"),axis.text.x=element_blank(), axis.ticks.x=element_blank())

```


# Vignette information

```{r reproducibility}
## Time spent creating this report:
diff(c(startTime, Sys.time()))

## Date this report was generated
message(Sys.time())

## Reproducibility info
options(width = 120)
devtools::session_info()
```

# Code for creating the vignette

```{r createVignette, eval=FALSE}
## Create the vignette
library('rmarkdown')
system.time(render('/dcl01/leek/data/sellis/barcoding/phenotype_vignettes/Prediction_Summaries.Rmd', 'BiocStyle::html_document'))
